runtime: python313
entrypoint: gunicorn -b :$PORT main:app --workers 4 --threads 4

instance_class: F1

inbound_services:
  - warmup

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 3
  max_instances: 25

env_variables:
  DB_HOST: "34.81.249.186"
  DB_NAME: "linebot_db"
  DB_USER: "root"
  DB_PASSWORD: "justin0706"
  DB_PORT: "5432"

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
